import { copyText } from '@/lib/clipboard';
import { useEffect, useState } from 'react';
import { apiGet, apiPost } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
type Skill = {existing?:{id:string;path:string};key:string;name:string;description:string;content:string;files:string[];source?:string;commit?:string;versionId?:string};
type Preview = {token:string;source:string;commit:string;skills:Skill[]};
export function TeamResources({onBack}:{onBack:()=>void}) {
  const [source,setSource]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[installed,setInstalled]=useState<Skill[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const refresh=()=>apiGet<{installed:Skill[]}>('/api/team-skills').then(x=>setInstalled(x.installed));
  useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
  async function load(){setBusy('preview');setError('');setPreview(null);try{setPreview(await apiPost('/api/team-skills/preview',{source}));}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  async function install(skill:Skill){if(!preview)return;setBusy(skill.key);setError('');try{const result=await apiPost<{reused?:boolean;existing?:{id:string;path:string}}>('/api/team-skills/install',{token:preview.token,key:skill.key});if(result.existing)setPreview(p=>p&&({...p,skills:p.skills.map(s=>s.key===skill.key?{...s,existing:result.existing}:s)}));await refresh();toast.success(result.reused?'本机已有相同技能，已复用，没有重复安装。':'已安装。返回 Agent，选择群，在 Skill 列表中勾选并保存。');}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  return <div className="space-y-6"><Button variant="ghost" onClick={onBack}>← 返回我的 Agent</Button>
    <header><h1 className="text-3xl font-semibold">团队资源</h1><p className="mt-2 text-muted-foreground">飞书保存项目资料，Git 分享工作方法，每台电脑独立安装与使用。</p></header>
    <section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">共享飞书资料</h2><div className="grid grid-cols-3 gap-3 text-sm">{['① 在飞书整理文档或资料清单','② 在 Agent 的群设置中导入链接','③ 检查权限、保存，按需读取原文'].map(t=><div key={t} className="rounded-lg bg-accent p-3">{t}</div>)}</div><p className="text-sm text-muted-foreground">同事共用原文，不复制文档内容。新链接需要导入一次；不会自动收录所有群消息。进入 Agent → 选择群，可使用“分享本群资料”和“从飞书导入资料清单”。</p><Button variant="outline" onClick={onBack}>选择 Agent，绑定群资料</Button></section>
    <section className="rounded-xl border p-5 space-y-4"><h2 className="text-lg font-semibold">从 Git 安装 Skill</h2><p className="text-sm text-muted-foreground">粘贴包含 SKILL.md 的仓库地址，先查看内容，再安装。支持 skills/名称/SKILL.md 目录。私有仓库使用本机已有的 Git HTTPS 登录。</p><div className="flex gap-2"><Input aria-label="Git 技能仓库地址" placeholder="https://github.com/你的团队/skills.git" value={source} disabled={!!busy} onChange={e=>{setSource(e.target.value);setPreview(null);}}/><Button disabled={!!busy||!source.trim()} onClick={load}>{busy==='preview'?'读取中…':'读取技能库'}</Button></div>
    {error&&<p role="alert" className="text-destructive text-sm">{error}</p>}
    {preview&&<><p className="text-xs text-muted-foreground break-all">版本 {preview.commit.slice(0,12)} · {preview.skills.length} 个技能 · 安装后不会自动启用或运行脚本</p>{preview.skills.map(s=>{const done=installed.some(i=>i.source===preview.source&&i.commit===preview.commit&&i.key===s.key);return <article key={s.key} className="border rounded-lg p-4 space-y-2"><div className="flex justify-between gap-3"><div><h3 className="font-medium">{s.name}</h3><p className="text-sm text-muted-foreground">{s.description}</p></div><Button disabled={!!busy||done||!!s.existing} onClick={()=>install(s)}>{s.existing?'本机已有 · 无需安装':done?'已安装':busy===s.key?'安装中…':'安装到本机'}</Button></div>{s.existing&&<p className="text-xs text-muted-foreground break-all">全部文件内容一致，复用本机技能：{s.existing.path}</p>}<details><summary className="cursor-pointer text-sm">查看技能内容与 {s.files.length} 个文件</summary><pre className="text-xs whitespace-pre-wrap max-h-72 overflow-auto bg-accent p-3 mt-2">{s.content}</pre><p className="text-xs whitespace-pre-wrap mt-2">{s.files.join('\n')}</p></details></article>;})}</>}
    </section>
    <section className="rounded-xl border p-5 space-y-3"><h2 className="text-lg font-semibold">本机已安装 · {installed.length}</h2><p className="text-sm text-muted-foreground">安装后：返回 Agent → 选择群 → 勾选 Skill → 保存并应用。更新时重新读取仓库、安装新版本，再切换本群选择；旧版本保留，可以切回。</p>{!installed.length&&<p className="text-sm">还没有通过团队技能库安装的 Skill。</p>}{installed.map(s=><div key={s.versionId} className="border-t pt-3 space-y-1"><div className="font-medium">{s.name} <span className="text-xs text-muted-foreground">{s.commit?.slice(0,12)}</span></div><p className="text-xs text-muted-foreground break-all">{s.source} · {s.key}</p><Button size="sm" variant="outline" onClick={async()=>{try{setError('');await copyText(`团队 Skill：${s.name}\n仓库：${s.source}\n目录：${s.key}\n已安装版本：${s.commit}\n在 feishu-collaborator → 团队资源中读取仓库并选择安装。读取的是仓库最新版本，请核对版本。`);toast.success('已复制 Skill 分享信息');}catch{setError('剪贴板不可用，请复制上方仓库地址');}}}>复制分享信息</Button></div>)}</section>
  </div>;
}
