import {useEffect,useState} from 'react';
import {advance,approve,changeRequirement,initialBoard} from './model';
import type {Board,Step} from './model';
import './coordinator.css';
const labels={pending:'待开始',running:'执行中',done:'已完成',approval:'等你确认'};
const storageName='coordinator-experience-v1';
function restore():Board {try {const x=JSON.parse(localStorage.getItem(storageName)||'null');if(x&&Array.isArray(x.steps)&&x.steps.length===5&&Array.isArray(x.events)&&['draft','active','paused','done'].includes(x.phase)&&['auto','manual'].includes(x.mode))return {...x,phase:x.phase==='active'?'paused':x.phase};}catch{}return initialBoard();}
export function CoordinatorDemo(){
 const [b,setB]=useState<Board>(restore),[selected,setSelected]=useState('product'),[note,setNote]=useState(''),[tab,setTab]=useState<'detail'|'records'>('detail');
 useEffect(()=>{try{localStorage.setItem(storageName,JSON.stringify(b));}catch{}},[b]);
 useEffect(()=>{if(b.mode!=='auto'||b.phase!=='active'||b.steps.some(s=>s.status==='approval'))return;const t=setTimeout(()=>setB(advance),3500);return()=>clearTimeout(t);},[b]);
 const s=b.steps.find(x=>x.id===selected)!;
 const complete=b.steps.filter(s=>s.status==='done').length;
 const pendingApproval=b.steps.some(s=>s.status==='approval');
 function log(message:string,patch:Partial<Board>){setB(x=>({...x,...patch,events:[message,...x.events]}));}
 function node(step:Step){return <button className={'co-node '+step.status+(selected===step.id?' selected':'')} onClick={()=>{setSelected(step.id);setTab('detail');}}><span className="co-node-top"><span className="co-role">{step.agent}</span><span className={'co-state '+step.status}>{labels[step.status]}</span></span><strong>{step.title}</strong><small>{step.status==='running'?'正在执行示例任务…':step.status==='done'?'查看交付与记录 ↗':step.id==='release'?'这一步始终由人决定':'按依赖顺序接力'}</small></button>}
 return <div className="co-app"><header className="co-header"><a href="?">◈ 协作工作台</a><span>项目 / OctoLead / 协调员体验</span><span className="co-demo">交互演示 · 非真实执行</span></header>
 <main className="co-main"><div className="co-heading"><div><span className="co-eyebrow">HUMANS + AGENTS</span><h1>你定方向，团队接力。</h1><p>把一个目标交给协调员，看看任务如何分配、交接，以及在你插话时停下来。</p></div><button className="co-reset" onClick={()=>{if(confirm('重新开始这次本地演示？')){setB(initialBoard());setNote('');}}}>重新体验 ↻</button></div>
 <div className="co-banner">这是可操作的流程演练：角色、执行和验收结果均为模拟，不发送飞书消息、不修改业务表、不运行代码或上线。刷新后自动暂停，保留本机进度。</div>
 <section className="co-goal"><div className="co-goal-label">任务 001 <span>需求版本 v{b.revision}</span></div>{b.phase==='draft'?<textarea aria-label="项目目标" value={b.goal} onChange={e=>setB({...b,goal:e.target.value})}/>:<h2>{b.goal}</h2>}<div className="co-toolbar"><div className="co-toggle" aria-label="协作模式">{(['manual','auto'] as const).map(m=><button aria-pressed={b.mode===m} className={b.mode===m?'active':''} onClick={()=>log(m==='manual'?'你切换为手动模式，自动推进已停止。':'你切换为自动模式。',{mode:m,phase:b.phase==='active'?'paused':b.phase})}>{m==='manual'?'手动协作':'协调员自动协作'}</button>)}</div><span className="co-summary">{b.phase==='draft'?'等待确认目标':b.phase==='paused'?'已暂停 · 不再派发':b.phase==='done'?'本轮体验已完成':pendingApproval?'需要你确认 · 上线阶段':`正在推进 · ${complete}/5 个节点完成`}</span>
 {b.phase==='draft'?<button className="co-primary" disabled={!b.goal.trim()} onClick={()=>log('你确认目标，协调员开始按职责分配任务。',{phase:'active'})}>确认目标，开始体验 →</button>:b.phase==='active'?<button onClick={()=>log('你暂停了任务；模拟执行已停止。',{phase:'paused'})}>暂停协作</button>:b.phase==='paused'?<button className="co-primary" onClick={()=>log(`你确认按 v${b.revision} 继续。`,{phase:'active'})}>确认并继续 →</button>:null}
 {b.mode==='manual'&&b.phase==='active'&&!pendingApproval&&<button className="co-primary" onClick={()=>setB(advance)}>手动推进一步</button>}</div></section>
 <div className="co-layout"><section className="co-flow"><div className="co-section-title"><h3>任务全景</h3><span>点击节点查看依据与交付</span></div><div className="co-flow-inner"><div className="co-single">{node(b.steps[0]!)}</div><div className="co-branch">↓　按模块并行分配　↓</div><div className="co-parallel">{node(b.steps[1]!)}{node(b.steps[2]!)}</div><div className="co-branch">└────── 汇合验收 ──────┘<br/>↓</div><div className="co-single">{node(b.steps[3]!)}</div><div className="co-arrow">↓</div><div className="co-single">{node(b.steps[4]!)}</div></div><div className="co-legend">○ 待开始　<span>● 执行中</span>　✓ 完成　<span className="amber">● 等待人工确认</span></div></section>
 <aside className="co-side"><div className="co-tabs"><button className={tab==='detail'?'active':''} onClick={()=>setTab('detail')}>任务详情</button><button className={tab==='records'?'active':''} onClick={()=>setTab('records')}>记录预览</button></div>{tab==='detail'?<><span className="co-eyebrow">{s.agent}</span><h3>{s.title}</h3><dl><dt>负责范围</dt><dd>{s.role}</dd><dt>执行依据</dt><dd>当前目标 v{b.revision}；{s.deps.length?'等待 '+s.deps.map(id=>b.steps.find(x=>x.id===id)?.title).join('、')+' 完成':'由协调员整理需求并明确验收标准'}</dd><dt>结果与证据</dt><dd>{s.status==='done'||s.status==='approval'?s.result:'尚无交付；未完成节点不会展示成已完成。'}</dd></dl></>:<><h3>团队共享记录</h3><p className="co-muted">本地演示记录，尚未写入飞书。</p>{b.steps.map(x=><div className="co-record" key={x.id}><strong>{x.title}</strong><span>{x.agent} · {labels[x.status]}</span><small>来源：人工目标 / 协调员分派 · v{b.revision}</small></div>)}</>}
 {pendingApproval&&<div className="co-approval"><strong>轮到你决定了</strong><p>模拟验收完成。自动模式会停在这里，等待你确认。</p><button className="co-primary" disabled={b.phase!=='active'} onClick={()=>setB(approve)}>确认模拟上线</button><button onClick={()=>log('你暂缓上线，任务保留待确认。',{phase:'paused'})}>暂缓，保留结果</button></div>}
 <div className="co-intervene"><h3>随时插一句</h3><textarea aria-label="补充要求" placeholder="例如：保留历史任务的数据，先别改后端。" value={note} onChange={e=>setNote(e.target.value)}/><button disabled={!note.trim()||b.phase==='draft'||b.phase==='done'} onClick={()=>{setB(x=>changeRequirement(x,note));setNote('');}}>补充要求并暂停</button><button disabled={b.phase==='draft'||b.phase==='done'} onClick={()=>log('你已接管，自动派发停止。可在手动模式继续。',{mode:'manual',phase:'paused'})}>人工接管</button></div></aside></div>
 <section className="co-log"><div className="co-section-title"><h3>协作动态</h3><span>每次分配与人工介入都有记录</span></div><div aria-live="polite">{b.events.slice(0,20).map((e,i)=><div className="co-event" key={b.events.length-i}><span>{String(b.events.length-i).padStart(2,'0')}</span><p>{e}</p></div>)}</div></section><footer>先试：开始自动协作 → 开发时补一句要求 → 确认继续 → 等测试完成 → 决定是否上线。</footer></main></div>;
}
